spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbs
    username: root
    password: Samira2012.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
